<<<<<<< HEAD
# Generated by Django 2.1 on 2019-06-07 21:56
=======
# Generated by Django 2.1 on 2019-06-08 07:40
>>>>>>> 90b49e1750d0429ba8e51d88a85821caa8c6f6f4

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
<<<<<<< HEAD
                ('title', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=4)),
                ('published_at', models.DateField()),
                ('detail', models.TextField()),
                ('image', models.ImageField(null=True, upload_to='media/')),
=======
                ('title', models.CharField(max_length=30)),
                ('category', models.CharField(max_length=10)),
                ('date', models.DateField()),
                ('text', models.TextField()),
                ('image', models.ImageField(upload_to='media/')),
>>>>>>> 90b49e1750d0429ba8e51d88a85821caa8c6f6f4
            ],
            options={
                'db_table': 'article',
            },
        ),
    ]
