# Generated by Django 2.1 on 2019-06-08 07:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=30)),
                ('category', models.CharField(max_length=10)),
                ('date', models.DateField()),
                ('text', models.TextField()),
                ('image', models.ImageField(upload_to='media/')),
            ],
            options={
                'db_table': 'article',
            },
        ),
    ]
