# Generated by Django 2.1 on 2019-06-08 16:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=10)),
                ('detail', models.TextField()),
                ('file', models.ImageField(null=True, upload_to='media/')),
                ('publish_start_at', models.DateField()),
                ('deleted', models.BooleanField(default=False)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('modified_at', models.DateField(auto_now=True)),
            ],
            options={
                'db_table': 'article',
            },
        ),
    ]
