# Generated by Django 2.1 on 2019-06-10 11:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company_data',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('category', models.CharField(max_length=10)),
                ('image', models.ImageField(upload_to='media/')),
            ],
            options={
                'db_table': 'company_data',
            },
        ),
    ]
